name = "vpn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

account_id = "1e8e94f6ff830886c374f17c19f200c1"
workers_dev = true

[[kv_namespaces]]
binding = "siren"
id = "83ec6506f55d4e5099836187eada645a"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "aacac2d2-cac8-442a-9f2c-4e4f807065f5"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/faprikaa/vpnv2ray/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/faprikaa/vpnv2ray/refs/heads/main/web/sub.html"
